- README.md
@derntl  @v1r0x : Removing project partners from the README
> Change of README

- README.md
I've added the funding informations to the README.md
> Added funding information to README

- lumen/.gitignore
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/Controllers/GpsController.php
- lumen/app/Http/Controllers/ImageController.php
- lumen/app/Http/Controllers/LiteratureController.php
- lumen/app/Http/Controllers/OptionsController.php
- lumen/app/Http/Controllers/SourceController.php
- lumen/app/Http/routes.php
- lumen/bootstrap/app.php
- lumen/database/migrations/2016_09_12_131526_create_users_table.php
- lumen/database/migrations/2016_09_29_111315_create_finds_table.php
- lumen/database/migrations/2016_09_29_112230_create_attributes_table.php
- lumen/database/migrations/2016_09_29_112246_create_context_attributes_table.php
- lumen/database/migrations/2016_09_29_112301_create_context_types_table.php
- lumen/database/migrations/2016_09_29_112309_create_context_values_table.php
- lumen/database/migrations/2016_09_29_112328_create_photo_table.php
- lumen/database/migrations/2016_09_29_112403_create_th_concept_table.php
- lumen/database/migrations/2016_09_29_112424_create_th_concept_label_table.php
- lumen/database/migrations/2016_09_29_112449_create_th_language_table.php
- lumen/database/migrations/2016_10_17_085306_create_sources_table.php
- lumen/database/migrations/2016_10_19_134442_create_th_broaders_table.php
- lumen/database/seeds/LanguageTableSeeder.php
I setup lumen with the desired functionality, but currently limited to one db connection.
Will update it to a more dynamic and flexible db connection setup, as soon as the user management has been implemented.
Please review @dirkseidensticker @derntl
> setup lumen

- index.html
please review @derntl @dirkseidensticker
> added missing bower ref

- lumen/database/migrations/2016_11_16_122736_add_misc_howpublished_to_bib_tex.php
- lumen/database/migrations/2016_11_16_123507_add_lasteditor_to_contextvalues.php
- lumen/database/migrations/2016_11_16_123535_add_lasteditor_to_finds.php
- lumen/database/migrations/2016_11_16_123544_add_lasteditor_to_sources.php
- lumen/database/migrations/2016_11_16_123951_add_lasteditor_to_ph_photos.php
Added new fields to 'bib_tex', 'context_values', 'finds', 'sources' and 'ph_photos'
> Database update

- app.js
- controllers/mainCtrl.js
- controllers/mapCtrl.js
- css/style.css
- includes/inputFields.html
- index.html
- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_US.json
- layouts/create-element.html
- layouts/delete-confirm.html
- lumen/app/Http/Controllers/ContextController.php
- testing.html
please review @derntl @dirkseidensticker
> ui tweaks and minor bug fixes

- app.js
- controllers/mainCtrl.js
- controllers/userCtrl.js
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/Controllers/ImageController.php
- lumen/app/Http/Controllers/UserController.php
- lumen/app/Http/routes.php
- lumen/bootstrap/app.php
- lumen/database/migrations/2016_11_09_000000_create_bib_tex_table.php
- lumen/database/migrations/2016_11_09_000001_create_attributes_table.php
- lumen/database/migrations/2016_11_09_000002_create_finds_table.php
- lumen/database/migrations/2016_11_09_000003_create_context_values_table.php
- lumen/database/migrations/2016_11_16_122736_add_misc_howpublished_to_bib_tex.php
- lumen/database/migrations/2016_11_16_154245_add_thesaurus_val_on_context_values.php
- lumen/database/migrations/2016_11_22_100652_add_type_column_to_bib_tex.php
Beside adding `nullable()` to some of the db columns (to allow `null` values) I fixed a couple of wrong column references.
Please review/merge @derntl @dirkseidensticker @Hvitgar
> Fix not nulls

- lumen/database/migrations/2016_11_22_100652_add_type_column_to_bib_tex.php
I corrected the typo within the migration concering the bib_tex-table.
> Corrected typo in last migration

- lumen/database/migrations/2016_11_22_134408_add_icon_options_finds.php
please review @derntl @dirkseidensticker
> add icon and color options to finds

- controllers/mainCtrl.js
- controllers/mapCtrl.js
- includes/inputFields.html
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/routes.php
- lumen/database/migrations/2016_11_22_134408_add_icon_options_finds.php
- map.html
It is (at least should be) now possible to clone elements in the tree view. The clone includes basic element information (name, lat, lng, ...) and attribute data but **NOT** children.
Please review and approve or request changes if this is not the intended behavior.
@derntl @dirkseidensticker @AngusLeBoeuf
> Duplicate elements

- controllers/mainCtrl.js
- controllers/mapCtrl.js
- includes/new-tree.html
- layouts/marker.html
- lumen/app/Http/Controllers/ContextController.php
This PR adds a new 'add element' item to the tree view (as first _and_ last element). It should also fix a couple of bugs in the element storing methods.
Please review @derntl @dirkseidensticker @AngusLeBoeuf
> added 'add new element' functionality to the tree view

- controllers/mainCtrl.js
- controllers/mapCtrl.js
- css/style.css
- includes/inputFields.html
- includes/new-tree.html
- index.html
- layouts/source-modal.html
- lumen/app/Http/Controllers/AnalysisController.php
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/Controllers/SourceController.php
- lumen/app/Http/routes.php
- testing.html
This started as a small bugfix branch, but had to add a couple of other fixes and enhancements.
Here's a short list of things which didn't work (because they were buggy or not implemented);
1. Add markers using the leaflet panel
2. Add/Remove source entries
3. Store dimensions/epochs
4. Removed unnecessary dummy elements and other small UI enhancements
5. Open datepicker popup
6. Store data not only in the database but local as well (no refresh of the site after adding/editing/removing data from an element)
Please review and give your feedback **ASAP** or merge.
@dirkseidensticker @derntl @AngusLeBoeuf 
Thanks in advance!
> Bugfixing and enhancements

- app.js
- controllers/mainCtrl.js
- controllers/mapCtrl.js
- controllers/subTreeCtrl.js
- controllers/userCtrl.js
- lumen/app/Http/Controllers/ContextController.php
1. Disable _New find_ and _New Context_ for a find's context menu
2. Due to the proxy setting I had to add `intern/` to the api url
3. Check for `null` value of the epoch object to avoid a PHP/HTTP 500-Error
Please review @derntl @dirkseidensticker @AngusLeBoeuf
> Tree fixes

- controllers/mainCtrl.js
- controllers/mapCtrl.js
- css/style.css
- testing.html
Please review @derntl @dirkseidensticker
> allow context renaming

- INSTALL.md
@derntl @dirkseidensticker @AngusLeBoeuf Please review. If you find anything wrong, unclear, etc. feel free to edit.
> add an installation guide for lumen and an additional proxy

- app.js
- controllers/mainCtrl.js
- controllers/mapCtrl.js
- controllers/subTreeCtrl.js
- controllers/userCtrl.js
Please review @derntl @dirkseidensticker @AngusLeBoeuf
> simplified api url

- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/Controllers/SourceController.php
- lumen/database/migrations/2017_01_11_141536_create-db-functions.php
Created a migration adding a new view which replaces the former used functions. Fixed #44
> Migrate db functions

- controllers/literatureCtrl.js
- index.html
- lumen/app/Http/Controllers/LiteratureController.php
- lumen/app/Http/routes.php
- testing.html
This PR adds a basic bibtex editor. On the backend side there is most of the logic (get entry by id, get all entries, add entry, edit entry), on the frontend side it is only possible to add an entry. There is currently no feedback. You can check the result if you click on a context on the left side and open the literature/possibility modal. In the dropdown menu you should see your element (last element in the list).
> Simple bibtex "editor"

- lumen/app/Http/Controllers/ContextController.php
Please merge @eScienceCenter/spacialists
> fix typos in context controller

- lumen/app/Context.php
- lumen/app/Geodata.php
- lumen/bootstrap/app.php
- lumen/composer.json
- lumen/database/migrations/2017_01_18_150738_create_geodata.php
Includes lumen postgis setup aswell as the new model and migration for the geodata table, adjustments were made to the contexts-model accordingly.
I tested the migration with randomly seeded data, transformation of lat/lng to geom and back worked. Please review @v1r0x @derntl
> Migrate postgis

- lumen/database/migrations/2017_01_22_162056_define_roles_and_permissions.php
Please merge @eScienceCenter/spacialists
> add missing permission to down method

- app.js
- app/mainService.js
- app/mapService.js
- controllers/mapCtrl.js
- includes/new-tree.html
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/routes.php
- view.html
Please review @dirkseidensticker
> fix several bugs related to the map popups

- app/mainService.js
- app/mapService.js
- controllers/mapCtrl.js
- css/style.css
- layouts/marker.html
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/routes.php
- view.html
Fix #78 
This PR should fix the bugs/enhancements described in #78, Please review @eScienceCenter/spacialists
> Map enhancements/fixes

- controllers/literatureCtrl.js
- controllers/mapCtrl.js
I forgot to add the `currentUser` to the literature controller. It should now be possible to add/remove/edit literature.
And I had to adjust a check whether to set an element or not after clicking on a geodata.
> small bugfixes

- app.js
> Update auth token on rejected response and display an error message

- controllers/userCtrl.js
Adding/Removing of user roles was not possible. Please test and merge @eScienceCenter/spacialists
> add missing add/remove role methods to controller

- app/imageService.js
- controllers/imageCtrl.js
Fix #74 
I tested it on our testing environment and the bugs should be fixed now. Could you please test it on your VMs @dirkseidensticker and @AngusLeBoeuf ?
> Fix photo tab bugs

- app.js
- app/literatureService.js
- controllers/literatureCtrl.js
- css/style.css
- literature.html
- lumen/app/Http/Controllers/LiteratureController.php
Fix #77 
The literature is now sortable by most of the columns. Searching is also possible and the header stays on top while scrolling.
> Literature page enhancements

- app.js
- app/mainService.js
- css/style.css
- includes/inputFields.html
- lumen/app/Http/Controllers/SourceController.php
- view.html
This PR adds a small green circle icon to the appropriate attribute behind the `+` icon.
@eScienceCenter/spacialists
> add 'has literature' indicator to attribute form

- app/mainService.js
- controllers/mainCtrl.js
- layouts/source-modal.html
- lumen/app/Http/Controllers/SourceController.php
- lumen/app/Http/routes.php
- view.html
This PR adds a bibliography to the main view. I also adjusted the attribute's bibliography popup layout to match the overview in the main view.
> Add bibliography tab

- app/mainService.js
- app/mapService.js
- controllers/mainCtrl.js
- controllers/mapCtrl.js
- css/style.css
- includes/inputFields.html
- includes/new-tree-child.html
- layouts/source-modal.html
- lumen/app/AvailableLayer.php
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/Controllers/OverlayController.php
- lumen/app/Http/routes.php
- lumen/database/migrations/2017_02_13_181504_add_possibility_description.php
- lumen/database/migrations/2017_02_14_140039_create_layerconfig_table.php
- view.html
This PR addresses the TODOs of the trello card. Additionally I added code to edit geojson objects. For a detailed description, see the commit messages or the trello card.
> Ui enhancements

- app/mainService.js
- app/mapService.js
- view.html
> disable legend for now

- app/mapService.js
- view.html
> set feature group on init to prevent duplicated controls

- controllers/mapCtrl.js
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/routes.php
> Remove geodata using Leaflet.Draw

- app.js
- app/userService.js
- controllers/userCtrl.js
- layouts/login.html
Fix #94 
Tried to fix issue #95 as well, but couldn't figure out how to tell the ui-router plugin to reload the page (controllers and services). I tried `$state.go('spacialist', {}, { reload: true });` and `$state.reload('spacialist');`. Maybe we have to fix it different...
> display error messages with same status code only once

- app/mainService.js
- css/style.css
- layouts/source-modal.html
Fix #101 
Revamps the certainty modal based on @derntl suggestions. Suggestions and a preview can be found in #101.
> Revamp certainty modal

- app/langService.js
- controllers/langCtrl.js
- index.html
It is now possible to switch between UI language using the dropdown in the upper left corner.
Please merge @eScienceCenter/spacialists
> make language switch possible again

- app.js
- app/analysisService.js
- controllers/mainCtrl.js
- controllers/userCtrl.js
- index.html
- view.html
> embed dbWebGen as dropdown

- app/mainService.js
- controllers/mainCtrl.js
- css/style.css
- view.html
> display info text if elem has no bibliography

- app/mainService.js
> Only add certainty description if it is set

- app/literatureService.js
- controllers/literatureCtrl.js
- literature.html
Fix #130 
Editing or deleting a specific entry in the literature list should now work as expected.
> do not use $index in sortable arrays

- controllers/userCtrl.js
> on logo click go back to spacialist state

- app/mainService.js
- app/mapService.js
- app/userService.js
- index.html
Fix #137 
Username should now be displayed correctly (only visible if the user is logged in). The map layers should also be visible after (re)login.
> Login fixes

- app/mainService.js
- lumen/app/Http/Controllers/ContextController.php
> New top-level context fix

- app/mainService.js
Fix #139 
Literature references should now appear even if it is the first entry.
> init literature array if undefined

- app/imageService.js
- controllers/imageCtrl.js
- lumen/app/Http/Controllers/ImageController.php
- view.html
Fix #142 
Due to a service/controller problem the progress bars were not visible. Now there should be a progress bar for each file. After all files are uploaded the progress bars are removed (after 1000ms). Is this ok or should there be more/another info? @derntl
> Image upload

- app/mainService.js
- app/mapService.js
- layouts/source-modal.html
- lumen/app/Http/Controllers/ContextController.php
Fix #148 
The problem was a reference to old code. Changing the context name should now be possible without an error.
> remove legacy update marker code

- app/mainService.js
- app/mapService.js
- controllers/mapCtrl.js
- includes/new-tree-child.html
- lumen/app/Http/Controllers/ContextController.php
Fix #162 
Tree should now expand right after startup to the correct element without any error. Please review @dirkseidensticker
> use own tree toggle logic

- lumen/database/migrations/2017_03_10_153046_add_role_management_permissions.php
- lumen/database/migrations/2017_03_15_192549_add_default_admin_account.php
This PR adds a default admin user account. Thus it is easier to add other users after initial setup.
> Default admin

- app/userService.js
- controllers/userCtrl.js
- user.html
Deleting a user in the UI was not possible, because of a missing reference in the user controller. I also modified the method of the service, so we are no longer depend on the `$index` of the angular array (which leads to bugs if we e.g. allow to reorder the user list).
> add missing 'delete user' reference

- includes/inputFields.html
Re-"adds" icons to the data model editor. Now it should be possible again to delete and move attributes (edit isn't implemented yet).
> replace old fa icons with md icons

- view.html
Fix #175 
Please review @AngusLeBoeuf
> just hide (not remove) map on tab switch

- app/literatureService.js
- controllers/literatureCtrl.js
- l10n/de.json
- l10n/en.json
- literature.html
- lumen/app/Http/Controllers/LiteratureController.php
- lumen/app/Http/routes.php
- lumen/composer.json
Fix #196 
This PR adds an importer to the footer in the literature view. It currently adds new/updated entries and skips existing ones. If the user edits one part of an entry in the bib file and upload it again, there will be a new entry.
Please review @eScienceCenter/spacialists 
**Please note:**
`composer update` required
> Bibtex importer

- app/literatureService.js
- lumen/app/Http/Controllers/LiteratureController.php
Follow-up of #203 
Catches the exception and displays it. Thus the user can see what's wrong with the file. Please review @eScienceCenter/spacialists
> catch exception

- app/mapService.js
- lumen/app/Http/Controllers/ContextController.php
Should be possible again to add polygons to the database. Please review @eScienceCenter/spacialists
> adjust add polygon method to new leaflet data structure

- includes/inputFields.html
- includes/tree.html
- layouts/add-attribute.html
- layouts/edit-contexttype.html
- layouts/marker.html
- layouts/new-context-type.html
plus, the "create top context" is now a button
> get rid of remaining font awesome icons

- app/mapService.js
- controllers/mapCtrl.js
- l10n/de.json
- l10n/en.json
- layouts/marker.html
- lumen/app/Http/Controllers/ContextController.php
- lumen/app/Http/routes.php
> Map enhancements

- app/imageService.js
> add missing translate di

- CONTRIBUTING.md
- INSTALL.md
- issue_template.md
This PR adds a `CONTRIBUTING.md` and `issue_template.md`. All new issues should be created using the `issue_template.md` file. I also added a section about different filesystem drivers for lumen. Thus it should be possible to test photo-related PRs on VMs.
> add contributing information

- app/analysisService.js
> Add timestamp to url to force ng-src reload

- view.html
How beautiful this looks now 😍
> fix context type label typo

- CHANGELOG.md
I added an changelog file so we can track bigger changes to spacialist in each PR. It's then easier to list all notable changes in the releases tab. Please review @eScienceCenter/spacialists
> added CHANGELOG.md file

- lumen/app/Http/Controllers/ContextController.php
Fix #240 
With this fix it should be possible to store epochs with and without exact dates.
Please review @eScienceCenter/spacialists and @DavidKi
> Fix epoch datatype

- CHANGELOG.md
Forgot to add the fix to the changelog file. Please merge @eScienceCenter/spacialists
> add epoch fix (refs #241)

- CHANGELOG.md
I added the two latest merges to the CHANGELOG.md file. Please merge @eScienceCenter/spacialists
> Add dynamic ui and layer control to changelog

- app/mapService.js
Add missing commit from original layers branch. Please merge @eScienceCenter/spacialists
> use marker instead of circlemarker for now

- app/imageService.js
- app/mainService.js
- controllers/imageCtrl.js
- view.html
This PR fixes two small issues reported from one of the projects.
1. [x] Childrens of search results in the tree view are not visible (only the expand arrow)
2. [x] _Show tags_ in the filter tab in the files tab has no effect (thus it is not possible to add tags to files)
> Fix search

- CHANGELOG.md
forgot to add latest changes to changelog....again
> Add new changes to changelog

- l10n/de.json
- l10n/en.json
The entry for the context datatype was missing. Please merge @eScienceCenter/spacialists
> update language files

- CHANGELOG.md
- app/mainService.js
- controllers/contextCtrl.js
- includes/form-fields.html
- lumen/app/Http/Controllers/FileController.php
While working on #238 I found out that the context search didn't work. I also fixed a bug with a malfunctioning `if`.
0.3.1 should be released after this is merged.
> Fix context search

- CHANGELOG.md
- app.js
- css/style.css
- l10n/de.json
- l10n/en.json
- layouts/login.html
- lumen/app/Http/Controllers/FileController.php
- lumen/database/seeds/RolesPermissionsSeeder.php
This PR fixes a couple of small bugs/issues within Spacialist. Spacialist should now keep running even if a file doesn't exist (on disk) anymore. I also added a spinner icon to the login screen, so people can see that Spacialist does _something_ and they don't have to click randomly on their screen 😉 
> Bugfix Release - 0.4.3

- CHANGELOG.md
- app.js
- app/fileService.js
- app/mainService.js
- components/spacialist.js
- lumen/app/Http/Controllers/ContextController.php
- modals/file.html
- view.html
Fix #296, fix #298, fix #299 
Hopefully the last bugfix release for the Delphi release. Please have a look at the changelog and/or commits for a full list of fixes.
> Bugfix Release - 0.4.4

- includes/form-fields.html
Resetting epoch to empty field works. Fixed #307
> Epoch entries can be cleared

- app/literatureService.js
- layouts/add-attribute-contexttype.html
- layouts/edit-contexttype.html
- layouts/new-context-type.html
- modals/add-attribute.html
- modals/add-bibliography.html
- modals/add-context.html
- modals/add-role.html
- modals/add-user.html
- modals/edit-role.html
- modals/edit-user.html
- modals/sources.html
- templates/context-data.html
- templates/layer-edit.html
Fix #262 
I added submit buttons to all forms mentioned in https://github.com/eScienceCenter/Spacialist/issues/262#issuecomment-349920794. I also added a disabled state for invalid input to some forms.
Please review @eScienceCenter/spacialists (and answer the questions in https://github.com/eScienceCenter/Spacialist/issues/262#issuecomment-351422346)
> make buttons/add submit buttons to forms

- app.js
- bibliography.html
- data-model.html
- helpers.js
Fix #305 
Map, Literature, Layer Editor and Data Model Editor should now have the correct height again. Please review @eScienceCenter/spacialists
> fix computed height of container elements

- l10n/de.json
- l10n/en.json
- templates/header.html
> Revamp header bar

- app.js
- components/spacialist.js
- controllers/contextCtrl.js
- helpers.js
- l10n/de.json
- l10n/en.json
- view.html
Another request from a meeting.
Adds a toggle to show/hide files linked to one of the (grand-*)children.
> Add linked files of child contexts to file viewer

- CHANGELOG.md
- database/migrations/2018_09_06_092028_setup_tables.php
- package.json
- resources/js/App.vue
- resources/js/components/EntityDetail.vue
- resources/js/components/EntityTree.vue
- resources/js/components/plugins/File3d.vue
- resources/js/components/plugins/MapGisPropertiesModal.vue
- resources/js/components/plugins/MapLayerEditorDetail.vue
- resources/sass/_datgui.scss
- resources/sass/app.scss
A couple of important fixes for Federsee release.
- Missing content in Chrome/WebKit/Blink browsers
- Migration from previous version
- Links to Data Analysis-Plugins
- Several style issues
> 0.6.1 Release

- CHANGELOG.md
- database/migrations/2018_09_06_092028_setup_tables.php
- resources/js/components/EntityDetail.vue
Fixed a bug in migrations causing errors on saving new values
> 0.6.2 Release

- CHANGELOG.md
- database/seeds/AdminUserSeeder.php
- database/seeds/DatabaseSeeder.php
- database/seeds/MapSeeder.php
- database/seeds/RolesPermissionsSeeder.php
Fix wrong function calls in roles seeders and add map seeder to fix errors related to missing unlinked layer and add an OSM map.
> Fix seeders

- resources/js/i18n/de.json
- resources/js/i18n/en.json
- resources/js/i18n/ja.json
Translations update from Digital Humanities Center - Weblate Instance for Spacialist/Spacialist UI
It also includes following components:
* Spacialist/Spacialist PHP
> Translations update from Digital Humanities Center - Weblate Instance

- CHANGELOG.md
Signed-off-by: Vinzenz Rosenkranz <vinzenz.rosenkranz@uni-tuebingen.de>
> Release 0.9.11

- CHANGELOG.md
- app/Notification.php
- app/Observers/EntityObserver.php
- package-lock.json
- package.json
delete notification when referenced entity is deleted
Signed-off-by: Vinzenz Rosenkranz <vinzenz.rosenkranz@uni-tuebingen.de>
> Release 0.9.12

- CHANGELOG.md
- app/Bibliography.php
fix mandatory check for bibliography entries
Signed-off-by: Vinzenz Rosenkranz <vinzenz.rosenkranz@uni-tuebingen.de>
> Release 0.9.13

- CHANGELOG.md
- resources/js/components/EntityDetail.vue
- resources/js/components/attribute/Bool.vue
- resources/js/components/attribute/Date.vue
- resources/js/components/attribute/Default.vue
- resources/js/components/attribute/Dimension.vue
- resources/js/components/attribute/Entity.vue
- resources/js/components/attribute/Epoch.vue
- resources/js/components/attribute/Float.vue
- resources/js/components/attribute/Geography.vue
- resources/js/components/attribute/Iconclass.vue
- resources/js/components/attribute/Integer.vue
- resources/js/components/attribute/List.vue
- resources/js/components/attribute/MultiChoice.vue
- resources/js/components/attribute/Percentage.vue
- resources/js/components/attribute/Rism.vue
- resources/js/components/attribute/SingleChoice.vue
- resources/js/components/attribute/String.vue
- resources/js/components/attribute/Stringfield.vue
- resources/js/components/attribute/Tabular.vue
- resources/js/components/search/Simple.vue
> [0.10] Fix attribute validation & attribute group handling

- CHANGELOG.md
- app/Bibliography.php
- app/Http/Controllers/BibliographyController.php
- app/Role.php
- database/migrations/2023_11_29_101237_add_more_bibtex_fields.php
- resources/js/components/BibliographyTable.vue
- resources/js/components/modals/bibliography/FieldSet.vue
- resources/js/components/modals/role/AccessControl.vue
- resources/js/components/modals/role/Add.vue
- resources/js/helpers/modal.js
- resources/js/i18n/de.json
- resources/js/i18n/en.json
Changes (from `CHANGELOG.md`):
- Adding roles without setting a preset
- Permission Overview not visible if new role without preset is added
- Save Permissions without changing state of _Moderation_ switch
- Deleting a bibliography entry
- Importing local file referenced in Bibtex import
- Typos in Translation files
- Updating bibliography entries
> [0.10] Several bug fixes (Roles and Bibliography)

- resources/js/components/EntityDetail.vue
- resources/js/components/attribute/List.vue
@Severino your changes look fine! I added a fix for the list attribute, because changes in a list never triggered a `change` event.
> [0.10] Fix dirty state after save not removed

- CHANGELOG.md
- resources/js/components/modals/entity/Reference.vue
> [0.10] Fix certainty slider values < 0 and > 100

- CHANGELOG.md
- resources/js/components/tree/Node.vue
- Speed-up tree rendering
- Simplify dropdown logic
- Fix styling of counter badge
> [0.10] Fix loading time in entity tree

- resources/js/components/CsvTable.vue
- resources/js/components/tools/csv/CsvSettings.vue
- resources/sass/_utilities.scss
Fixes delimiter setting breaking into new lines when custom input is active
> [0.10] Fix csvsettings class

- resources/js/bootstrap/store.js
- resources/js/components/AttributeList.vue
- resources/js/components/forms/indicators/ValidityIndicator.vue
- resources/js/components/modals/entity/Reference.vue
- resources/js/helpers/helpers.js
- resources/sass/_bootstrap.scss
Fixed some issues for the 0.10-style-certainty:
+ Moved the certainty icons to an own component
+ Adjusted helper functions for certainty
+ Fixed the icon not being updated after change
+ Some small styling changes
> Update Certainty Style

- app/AttributeTypes/Units/Implementations/ForceUnits.php
- app/AttributeTypes/Units/Implementations/LengthUnits.php
- app/AttributeTypes/Units/Implementations/PressureUnits.php
- app/AttributeTypes/Units/Implementations/QuotientUnits.php
- app/AttributeTypes/Units/Implementations/SpeedUnits.php
- app/AttributeTypes/Units/Implementations/UnitManager.php
- app/AttributeTypes/Units/Implementations/VolumetricFlowUnits.php
- app/AttributeTypes/Units/UnitSystem.php
- composer.json
- composer.lock
- config/logging.php
- resources/js/i18n/de.json
- resources/js/i18n/en.json
- tests/Unit/Attributes/SiAttributeTest.php
Added
- Force
- Speed
- Pressure
- Volumetric Flow
- Quotients
> 0.10 additional si units

- CHANGELOG.md
- app/AttributeTypes/DaterangeAttribute.php
- app/Import/EntityImporter.php
- database/seeders/EntityAttributesTableSeeder.php
- lang/de/entity-importer.php
- lang/en/entity-importer.php
- package.json
- resources/js/components/AttributeList.vue
- resources/js/components/attribute/Attribute.vue
- resources/js/components/attribute/Daterange.vue
- resources/js/components/attribute/Richtext.vue
- resources/js/components/attribute/Serial.vue
- resources/js/components/attribute/Sql.vue
- resources/js/components/error/ErrorList.vue
- resources/js/components/modals/system/MarkdownEditor.vue
- resources/js/components/tools/importer/EntityAttributeMapping.vue
- resources/js/components/tools/importer/EntityImporterSettings.vue
- tests/Feature/ApiDataImporterTest.php
* Fix Date Range import, enhance error handling, and add tests for attribute mapping
* Fixed data range frontend and sort dropdown options alphabetically in Data Importer and
* Fixed richtext not triggering dirty state
* Ensure certainty is null and not undefined
* Fixed Serial and SQL attribute breaking the form validation
> Release 0.10.2 (#544)

- CHANGELOG.md
- app/Http/Controllers/EditorController.php
- resources/js/components/AttributeList.vue
- resources/js/components/DataModel.vue
- resources/js/components/dme/AttributeUsageIndicator.vue
- resources/js/i18n/de.json
- resources/js/i18n/en.json
Adds a usage indicator to the entity type list.
This is a cherry pick of  #519
> [0.11] feat attribute indicator (cherry pick)

- app/Bibliography.php
- app/File/Directory.php
- app/File/FileDirectory.php
- app/Http/Controllers/BibliographyController.php
- app/Http/Controllers/UserController.php
- app/User.php
- resources/js/helpers/helpers.js
Added a FileDirectory class that should handle all files inside one directory.
And prevents foreign files to be tempered with.
> [0.11] feat private files cp review sev

- CHANGELOG.md
- app/Bibliography.php
- app/File/Directory.php
- app/File/DownloadHandler.php
- app/File/FileDirectory.php
- app/Http/Controllers/BibliographyController.php
- app/Http/Controllers/UserController.php
- app/User.php
- config/filesystems.php
- database/migrations/2024_12_04_073048_make_files_private.php
- resources/js/api.js
- resources/js/bootstrap/stores/bibliography.js
- resources/js/bootstrap/stores/user.js
- resources/js/components/BibliographyTable.vue
- resources/js/components/UserAvatar.vue
- resources/js/components/bibliography/Citation.vue
- resources/js/components/modals/bibliography/Details.vue
- resources/js/components/modals/bibliography/Item.vue
- resources/js/helpers/helpers.js
- routes/web.php
- tests/Feature/ApiBibliographyTest.php
- tests/Feature/ApiEntityTest.php
- tests/Feature/ApiUserTest.php
> [0.11] Move files to private storage
