app.js, controllers/userCtrl.js
The new _main_ route is now `/#/spacialist/`. The old version still exists (`/#/old`).
User access should work again. Currently there are no protected routes, so it can not be tested right now.
Any suggestions which routes should be protected, @eScienceCenter/spacialists ?
=> updated route urls, fixed user access and code style improvements

app.js, css/style.css, includes/new-tree.html, index.html, testing.html
Height of the container elements now matches the current viewport height. Thus there should be no scrolling in the outer div, but for each container (tree, attributes, map).
=> set (max)height of elements to current viewport height

app/mainService.js, includes/new-tree-child.html, lumen/app/Http/Controllers/ContextController.php, lumen/app/Http/routes.php
Fix #72 
The time for loading the contexts and for creating the tree should be much faster now. Element data is now retrieved after a click on the element/geodata. Thus we only need 500ms instead of 10s (for the currently biggest project) and changes on one machine should now be visible on other machines without reload. Retrieving the data for only one element instead of all (~600) it is almost instantly.
The code for the tree expansion (if the user clickes on a connected geodata) is now more complex and slower. But again, the loading time (which also freezes the app) is down from ~5s to < 1s.
Please review and comment if we should accept the laggy tree expansion but therefore display the tree almost instantly. @eScienceCenter/spacialists
=> Improve loading time

app/mainService.js
In the bibliography tab the source entries from the previous selected element are still visible if the user deselects an element.
=> Unset sources as well

lumen/app/Http/Controllers/ContextController.php
Fix #100 
It seems that `'null'`is an array in PHP... :rage: 
=> check if value is null

app.js
This should redirect the user to the login page if a request returns http code 400 or 401 (e.g. wrong password, token invalid, <something else is wrong with the token>).
=> remove user from storage if error 400/401 occured

app/mainService.js, l10n/de.json, l10n/en.json, lumen/app/Http/Controllers/ContextController.php, lumen/app/Http/Controllers/LiteratureController.php, lumen/database/migrations/2017_03_01_101631_add_lasteditor_geodata_literature.php, view.html
This PR adds a `lasteditor` column to the `geodata` and `literature` table. Furthermore it adds the last editor and the last edit timestamp to the context properties tab. Are there any other places where we should display these informations?
@eScienceCenter/spacialists
=> Add more last modified

includes/inputFields.html
This PR removes the classes from the epoch select2 dropdown. With this classes it had non-bootstrap styling. Now it should look as all other input fields.
=> remove unnecessary styling

includes/new-tree-child.html
Fix #155 
Line breaks should now align correct beside the child toggle.
=> fix ugly indent on line break in tree

index.html, lumen/app/Http/Controllers/UserController.php, lumen/database/migrations/2017_01_22_162056_define_roles_and_permissions.php, lumen/database/migrations/2017_03_10_153046_add_role_management_permissions.php, roles.html
This PR adds the missing permissions from #157.
Now, columns in the role view should only be visible if the user has the appropriate permissions. On the server-side it should no longer be possible to add/edit/delete roles without the permission.
=> Role editor permissions

app/mainService.js, app/mapService.js, lumen/database/migrations/2017_03_13_134710_unique_geodata_id.php
Fix #151 
It should now no longer be possible to link a geodata object to multiple contexts (popup should close if it is connected to a context).
=> close previous popup if unlinked element is selected & was linked

app/mapService.js, view.html
Fix #163 
max zoom level is now at 27, which is about 1.5-2ft (less than 1m) on the map.
=> set max-zoom to appropriate value (27 = ~1.5ft)

lumen/database/seeds/GuestUserSeeder.php
This PR adds the possibility to add a guest user account. To add the guest user you have to exec the following two commands from within the lumen folder:
```bash
composer dump-autoload # otherwise the GuestUserSeeder file is not defined
php artisan db:seed --class=GuestUserSeeder
```
=> added seeder to add a guest user

app/userService.js
This PR checks if the user object exists in localStorage and redirects to the login page if not. Thus it is no longer possible to login, delete the content of the user object (or access the `#/spacialist` state directly without a user object) and then only see the "You are not allowed to access this page...." in all tabs without an option to re-login.
=> add check if user object exists

app/mapService.js, controllers/mapCtrl.js, layouts/marker.html, lumen/app/Context.php, lumen/app/Geodata.php, lumen/app/Http/Controllers/ContextController.php, lumen/app/Http/routes.php, lumen/database/factories/ModelFactory.php, lumen/database/migrations/2017_01_22_162056_define_roles_and_permissions.php, lumen/database/migrations/2017_03_10_153046_add_role_management_permissions.php, lumen/database/migrations/2017_03_28_115827_move_color_to_geodata.php, lumen/database/seeds/RandomSeeder.php
Colors can now be assigned to polygons and markers. Former used icons are no longer available as discussed in #176. When migrating existing projects, these icons will be translated into different colors.
Resolves #176
=> Show colors for geodata

lumen/composer.json
The entrust plugin has a release tag where we no longer need the fixes to use entrust.
`composer update` is required.
Please merge @eScienceCenter/spacialists
=> Use updated entrust version

app.js, app/imageService.js, app/mainService.js, app/userService.js, css/style.css, index.html, l10n/de.json, l10n/en.json
Fix #65 
This adds a snackbar-like popup to "silent" actions to the bottom left corner of the screen. The snackbar supports several types (success, info, warning and error). We could replace the current warning popup (which does not allow any interaction (e.g. try again, ignore, ...)) with snackbars.
If you find any "silent" action which does not open a snackbar, please add a comment. Otherwise please merge @eScienceCenter/spacialists 
Hint: Snackbars should appear for store context, delete context, edit user, add/remove roles, add/remove permissions and maybe others I already forgot.
=> Visual input feedback

app/mapService.js
Layers like WMS from the Geoserver where only displayed to a rather low zoom level. With this change the default value that is set further above is also set for every (external) layer. Like that all layers can be viewed in high detail.
=> Sets the maxZoom for all layers, including the Geoserver-WMS

app.js, includes/tree-child.html, includes/tree.html, view.html
Fix #106 
This re-adds a spinner while the tree is loading. I also renamed `new-tree.html` and `new-tree-child.html`. Please review @eScienceCenter/spacialists
=> display spinner if tree not retrieved yet, rename new-*

app.js, app/environmentService.js, app/mainService.js, controllers/mainCtrl.js, includes/tree-child.html, includes/tree.html, view.html
Fix #174 
This PR adds a search bar above the context tree. Due to the new context data layout it is only possible to keep the tree structure on search. Thus non-matching elements are still visible if one of their (grand)children is visible (aka matches the search term). Please review @eScienceCenter/spacialists
=> Add search bar

l10n/de.json
Changed the text for the evidence.certainty.heading from "Konfidenz in die Wertzuweisung" to "Sicherheit der Angabe".
=> evidence.certainty.heading changed

includes/inputFields.html
The placeholders are not necessary and are only showing the same information as the label of the input element. Hence they can be removed.
@eScienceCenter/spacialists Please review!
=> remove placeholders from text fields

app/mainService.js, controllers/mainCtrl.js, includes/inputFields.html, l10n/de.json, l10n/en.json, lumen/app/Http/Controllers/ContextController.php, lumen/app/Http/routes.php
Fix #230 
With this PR it is possible to reference a context in another context's attribute. On our testing machine I already added an attribute with the new `context` datatype and added it to the Library contexttype.
=> add reference to another context as datatype

css/style.css, includes/inputFields.html, view.html
At the moment a lot of space is wasted within the forms. This change sets all the marings and the padding to 0 to get as much information displayed as possible.
What do you think?
Please review and comment (but **don't merge**) @eScienceCenter/spacialists
=> Sets margins and padding to 0

app/mainService.js, controllers/mainCtrl.js, lumen/app/Http/Controllers/ContextController.php, lumen/database/migrations/2017_06_23_122655_set_dt_val_to_date.php
Fix #243 
The old column datatype is `timestamp with time zone`, but we are only interested in the date, not the time. Therefore I "changed" the type from `ts /w tz` to `date`. I also had to adjust the store and load methods, because dates were stored in `str_val`, not in `dt_val` :roll_eyes: 
Please review @eScienceCenter/spacialists (don't forget to run `php artisan migrate`)
fyi @DavidKi
=> Fix date (attribute type)

css/style.css
Currently, the progress, which we are using to register confidence within the sources popup is very slim. This gives it a sufficient height to work with.
@eScienceCenter/spacialists please review and merge
=> Updated style to increase height of progress bars

bower.json
Leaflet 1.1 is released and has some breaking API changes. With this PR max leaflet version is 1.0.x. Please merge @eScienceCenter/spacialists
=> Restrict leaflet to 1.0.x

controllers/mainCtrl.js
The unit of the `dimension` attribute type was missing in the context properties tab. Please review @eScienceCenter/spacialists
=> add missing dimension reference

CHANGELOG.md, app/mainService.js, includes/inputFields.html, l10n/de.json, l10n/en.json, lumen/app/Http/Controllers/ContextController.php
Fix #266, fix #270 
- Booleans (checkboxes) are now available as datatype.
- `string-sc` (Single Dropdown) values can now be removed (using the bold _x_ on the right-hand side of the dropdown)
=> Some new features

app/mainService.js
On current master int values are stored in the db, but not displayed in the UI. The problem is that on ui-side JS tries to parse `str_val` as int, but in the db we moved int values from `str_val` to `int_val`.
=> int values are stored in int_val, not str_val anymore

app/dataEditorService.js, controllers/threeCtrl.js, helpers.js, index.html, layouts/image-properties.html
I updated to newer versions of our used loaders. They are now both capable of listen for an onProgress event (download). The OBJLoader can now also display several objects instead of only one.
I had to remove our custom `swap` method from `Array`, because three.js doesn't check for own properties which lead to `XY is undefined` error messages.
The onProgress event listener is not perfect, because it only tracks the progress of the file download. Parsing the model consumes more time and blocks the browser UI. Thus we can display the download progress, but not the whole loading time. Consider this limitation before merging it.
=> 3D Viewer updates

templates/header.html
So that the users can easily find the manual, which is provided through the GitHub-Wiki, I've added a helper-icon at the farthest right of the menu bar.
@eScienceCenter/spacialists please review and merge once ok
=> Added helper icon

INSTALL.md, controllers/pdfCtrl.js, controllers/threeCtrl.js, layouts/pdf.html, lumen/app/Helpers.php, lumen/app/Http/Controllers/FileController.php, lumen/app/Http/routes.php, lumen/bootstrap/app.php, lumen/composer.json, modals/file.html
This PR replaces the (mostly used) static storage driver with a dynamic one. Some of the required steps are already described in the [INSTALL.md](https://github.com/eScienceCenter/Spacialist/blob/master/INSTALL.md#external-storage). Additionally, a new `env` setting `SP_FILE_DRIVER` is required. It has to be set to one of the keys/names in the `config>filesystems>disks` array in `bootstrap/app.php`.
Supported (useful) drivers are
- AWS
- (S)FTP
- WebDAV
Please feel free to setup a (s)ftp or aws driver an test it. If there are no major issues, this could be merged in 0.5. :) @eScienceCenter/spacialists
=> Allow different storage types (e.g. (S)FTP, AWS)

controllers/gisCtrl.js, modals/gis-import.html, templates/gis.html
Fixes based on a meeting last week.
- Visible Checkbox in Layer Editor correctly used in GIS editor
- Layer Control with user-added layers (no context-type layers) added to import preview
- If contexts are linked to geodata, their names are displayed in the GIS editor as well
=> Several GIS fixes

app/Http/Controllers/BibliographyController.php
Bibtex was created with the format of:
attr: {value}
but is specified as:
attr = {value}
This was fixed now.
=> Fixed wrong exported format

app/AttributeTypes/IconclassAttribute.php, resources/js/components/EntityDetail.vue, resources/js/i18n/de.json, resources/js/i18n/en.json
1. After reworking how entity data is stored, the structure of returned data has changed. I forgot to update the location of the entity name in the success toast
2. Iconclass attribute had the wrong column in `$field`
=> [0.10] fix misc

resources/js/components/map/InteractiveMap.vue
Moves the offset a bit up that it is no longer clipping the point.
=> add offset to overlay

CHANGELOG.md, app/Http/Controllers/BibliographyController.php, resources/js/components/BibliographyTable.vue
Fixing the file explorer not showing .bib and .bibtex files on windows.
Somehow the 'extension' prop of the file-upload component was not applied.
So I added it to the accept prop (which shold be internally merged anyways, as it is the
only available attribute on the input element where it has an effect).
Tested on Windows and MacOs.
=> 0.10 fix bibtex files non selectable on win mac

CHANGELOG.md, app/AttributeTypes/DaterangeAttribute.php, app/Import/EntityImporter.php, database/seeders/EntityAttributesTableSeeder.php, lang/de/entity-importer.php, lang/en/entity-importer.php, resources/js/components/attribute/Daterange.vue, resources/js/components/error/ErrorList.vue, resources/js/components/tools/importer/EntityAttributeMapping.vue, resources/js/components/tools/importer/EntityImporterSettings.vue, tests/Feature/ApiDataImporterTest.php
- Fixed Date Range _importFrom_ to return a JSON string
- Fixed Date Range component in the frontend
- Added tests to _ApiDataImporterTest_ to check if the same columns can be used in multiple attributes
- Added in testing data an attribute (_'Aufbewahrung' [string]_) to the entity type _'Fundstelle'_
- Changed the row error from just sending the column name to also send the column value
- Dropdowns in the _Data Importer_ are now sorted alphabetically, both the order of the attribute mappings and the option lists inside the dropdowns
- The ErrorList component of the Data Importer in the Frontend now preserves text inside `{{...}}`
=> 0.10.2 importer fix

app/AttributeTypes/SqlAttribute.php, app/Http/Controllers/EntityController.php, routes/api.php
When using the sql attribute without specifying the *:entity_id* parameter, then an error was thrown. 
This PR allows queries to not have this attribute and the funcitonality was moved to the SqlAttribute.php to make the Controller cleaner.
=> [0.11] fix sql attribute without entity

app/Exceptions/CsvColumnMismatchException.php, app/Exceptions/Structs/AttributeImportExceptionStruct.php, app/File/Csv.php, app/File/Parser.php, app/Http/Controllers/EntityController.php, app/Import/EntityImporter.php, app/Import/ImportResolution.php, lang/de/entity-importer.php, lang/en/entity-importer.php, tests/Feature/ApiDataImporterTest.php
I tried to import a CSV without a header. And noticed that it fails.
This pull request fixes that and adds all tests for the 'NoHeaders' variant.
=> Fixed importer when header is not present and row numbers are used.
